[package]
name = "simple_fluid_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
rand = "0.9.1"
rand_distr = "0.5.1"
rand_pcg = "0.9.0"

[[bin]]
name = "simple_fluid_simulation"
path = "src/main.rs"
